/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import modelo.ModelGestionPartidos;
import javax.swing.JOptionPane;
import controlador.GestionPartidoController;
import java.time.LocalDate;
import java.time.*;
import javax.swing.ButtonGroup;
import javax.swing.table.DefaultTableModel;
public class GestionPartidosV extends javax.swing.JInternalFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GestionPartidosV.class.getName());
    private final DefaultTableModel modeloPartido = new DefaultTableModel(new Object[]{"ID", "Equipo Local", "Equipo Visitante", "Fecha", "Estadio", "Cuidad", "Capacidad", "Estado", "Fase"}, 0);
    private final GestionPartidoController controlador = new GestionPartidoController();
    private int idSelected = 0;
    
    
    

    /**
     * Creates new form GestionPartidosV
     */
    public GestionPartidosV() {
        initComponents();
        setClosable(true);
        setMaximizable(true);
        setResizable(true);
        Cuidades();
        fases();
        jtPartidos.setModel(modeloPartido);
        cargarPartidos();
        
        
        ButtonGroup grupoRadios = new ButtonGroup();
        
        grupoRadios.add(rbDisponible);
        grupoRadios.add(rbFinalizado);
        grupoRadios.add(rbCancelado);
        rbDisponible.setSelected(true);
    }
    
    private void Cuidades(){
        cbCuidad.addItem("Selecciona una ciudad");
        cbCuidad.addItem("Ciudad de Guatemala");
        cbCuidad.addItem("Chimaltenango");
        cbCuidad.addItem("Quetzaltenango");
        cbCuidad.addItem("Mazatenango");
        cbCuidad.addItem("Mixco");
        cbCuidad.addItem("Cobán");
        cbCuidad.addItem("San Marcos");
        cbCuidad.addItem("Antigua Guatemala");
    }
    
    private void fases(){
        if (txtLocal.equals("") && txtVisitante.equals("")){
            cbFase.addItem("Ingresa un partido");
        
        }else{
            cbFase.addItem("Selecciona una fase");
            cbFase.addItem("FASE DE GRUPOS");
            cbFase.addItem("DECISEISAVOS");
            cbFase.addItem("OCTAVOS");
            cbFase.addItem("CUARTOS");
            cbFase.addItem("SEMIFINAL");
            cbFase.addItem("FINAL");
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtLocal = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtVisitante = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtFecha = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        cbCuidad = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        cbEstadio = new javax.swing.JComboBox<>();
        txtCapacidad = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        rbDisponible = new javax.swing.JRadioButton();
        rbFinalizado = new javax.swing.JRadioButton();
        rbCancelado = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtPartidos = new javax.swing.JTable();
        btnGuardar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        cbFase = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Equipo Local:");

        txtLocal.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Equipo Visitante:");

        txtVisitante.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Fecha:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Cuidad:");

        cbCuidad.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        cbCuidad.addActionListener(this::cbCuidadActionPerformed);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("Estadio:");

        cbEstadio.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

        txtCapacidad.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtCapacidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCapacidadKeyTyped(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("Capacidad:");

        rbDisponible.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        rbDisponible.setText("Disponible");
        rbDisponible.addActionListener(this::rbDisponibleActionPerformed);

        rbFinalizado.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        rbFinalizado.setText("Finalizado");

        rbCancelado.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        rbCancelado.setText("Cancelado");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setText("Estado:");

        jtPartidos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtPartidos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtPartidosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtPartidos);

        btnGuardar.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnGuardar.setText("Crear Partido");
        btnGuardar.addActionListener(this::btnGuardarActionPerformed);

        btnActualizar.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(this::btnActualizarActionPerformed);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setText("Fase:");

        cbFase.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1)
                                .addComponent(jLabel3)
                                .addComponent(jLabel5))
                            .addGap(314, 314, 314))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(rbDisponible)
                            .addGap(56, 56, 56)
                            .addComponent(rbFinalizado)
                            .addGap(61, 61, 61)
                            .addComponent(rbCancelado)
                            .addGap(17, 17, 17))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(cbEstadio, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtLocal, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtFecha, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 339, Short.MAX_VALUE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(361, 361, 361)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel8)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(txtVisitante, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel4)
                    .addComponent(jLabel6)
                    .addComponent(cbCuidad, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtCapacidad)
                    .addComponent(cbFase, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 794, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addComponent(btnGuardar)
                .addGap(92, 92, 92)
                .addComponent(btnActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtLocal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtVisitante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(52, 52, 52)
                                .addComponent(jLabel3))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbCuidad, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbEstadio, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCapacidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rbDisponible)
                            .addComponent(rbFinalizado)
                            .addComponent(rbCancelado)
                            .addComponent(cbFase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(83, 83, 83)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(116, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        if(!validarCampos())return;
        LocalDate fecha = txtFecha.getDate().toInstant().atZone(java.time.ZoneId.systemDefault()).toLocalDate();
        String estado = "";
        if(rbDisponible.isSelected()){
            estado = "DISPONIBLE";
        }else if (rbFinalizado.isSelected()){
            estado = "FINALIZADO";
        }else if(rbCancelado.isSelected()){
            estado = "CANCELADO";
        }
        
        
        if(Float.parseFloat(txtCapacidad.getText())<=0){
            JOptionPane.showMessageDialog(null, "Ingresa un valor valido");
        }else{
            
            controlador.NuevoPartido(txtLocal.getText(), txtVisitante.getText(),
            fecha, cbEstadio.getSelectedItem().toString(), cbCuidad.getSelectedItem().toString(), 
                    Integer.parseInt(txtCapacidad.getText()), estado, cbFase.getSelectedItem().toString());
        }
        cargarPartidos();
        
    }//GEN-LAST:event_btnGuardarActionPerformed

    public void cargarDatosCampos(){
        int fila = jtPartidos.getSelectedRow();
        
        if (fila ==-1)return;
        idSelected = Integer.parseInt(jtPartidos.getValueAt(fila, 0).toString());
        txtLocal.setText(jtPartidos.getValueAt(fila, 1).toString());
        txtVisitante.setText(jtPartidos.getValueAt(fila, 2).toString());
        LocalDate fecha = LocalDate.parse(jtPartidos.getValueAt(fila, 3).toString());
        txtFecha.setDate(java.sql.Date.valueOf(fecha));
        cbEstadio.setSelectedItem(jtPartidos.getValueAt(fila, 4).toString());
        cbCuidad.setSelectedItem(jtPartidos.getValueAt(fila, 5).toString());
        txtCapacidad.setText(jtPartidos.getValueAt(fila, 6).toString());
        cbFase.setSelectedItem(jtPartidos.getValueAt(fila, 8));
        
        String estado = jtPartidos.getValueAt(fila, 7).toString();
        
        
    }
    
    private void cbCuidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbCuidadActionPerformed
        // TODO add your handling code here:
        
        String seleccion =cbCuidad.getSelectedItem().toString();
        cbEstadio.removeAllItems();
        
        switch(seleccion){
            case "Ciudad de Guatemala":
                cbEstadio.addItem("Estadio Nacional Doroteo Guamuch Flores");
                cbEstadio.addItem("Estadio Manuel Felipe Carrera El Trébol");
                cbEstadio.addItem("Estadio Cementos Progreso");
                cbEstadio.addItem("Estadio Revolución");
                break;
            case "Chimaltenango":
                cbEstadio.addItem("Estadio Municipal de Chimaltenango");
                break;
            
            case "Quetzaltenango":
                cbEstadio.addItem("Estadio Mario Camposeco");
                cbEstadio.addItem("Estadio Israel Barrios");
                break;
                
            case "Mazatenango":
                cbEstadio.addItem("Estadio Municipal Carlos Salazar Hijo");
                break;
                
            case "Mixco":
                cbEstadio.addItem("Estadio Santo Domingo Guzmán");
                break;
                
            case "Cobán":
                cbEstadio.addItem("Estadio José Ángel Rossi");
                cbEstadio.addItem("Estadio INJUD");
                break;
                
            case "San Marcos":
                cbEstadio.addItem("Estadio Marquesa de la Ensenada");
                cbEstadio.addItem("Estadio Municipal de San Marcos");
                break;
                
            case "Antigua Guatemala":
                cbEstadio.addItem("Estadio Pensativo");
                break;
            
            default:
                cbEstadio.addItem("Ingresa una cuidad primero");
                break;
                
            
        }
        
        
        
        
    }//GEN-LAST:event_cbCuidadActionPerformed

    
    private boolean validarCampos() {//FUNCION PARA QUE COMPRUEBE SI ESTAN LLENOS TODOS LOS CAMPOS
    if (txtLocal.getText().trim().isEmpty()) {
        JOptionPane.showMessageDialog(this, "El equipo local es obligatorio.", "Error", JOptionPane.ERROR_MESSAGE);
        txtLocal.requestFocus();
        return false;
    }
    if (txtVisitante.getText().trim().isEmpty()) {
        JOptionPane.showMessageDialog(this, "El equipo visitante es obligatorio.", "Error", JOptionPane.ERROR_MESSAGE);
        txtVisitante.requestFocus();
        return false;
    }
    if (txtFecha.getDate() == null) {
        JOptionPane.showMessageDialog(this, "La fecha es obligatoria.", "Error", JOptionPane.ERROR_MESSAGE);
        return false;
    }
    if (cbEstadio.getSelectedItem() == null || cbEstadio.getSelectedItem().toString().equals("Selecciona una cuidad")) {
        JOptionPane.showMessageDialog(this, "El estadio es obligatorio.", "Error", JOptionPane.ERROR_MESSAGE);
        return false;
    }
    if (cbCuidad.getSelectedItem() == null || cbCuidad.getSelectedItem().toString().equals("Selecciona una ciudad")) {
        JOptionPane.showMessageDialog(this, "La ciudad es obligatoria.", "Error", JOptionPane.ERROR_MESSAGE);
        return false;
    }
    if (txtCapacidad.getText().trim().isEmpty()) {
        JOptionPane.showMessageDialog(this, "La capacidad es obligatoria.", "Error", JOptionPane.ERROR_MESSAGE);
        txtCapacidad.requestFocus();
        return false;
        
    
    }
    if(cbFase.getSelectedItem() == null || cbCuidad.getSelectedItem().toString().equals("Selecciona una fase")){
        JOptionPane.showMessageDialog(this, "Ingresa una Fase.", "Error", JOptionPane.ERROR_MESSAGE);
        return false;
    }
    return true;
}
    
    private void rbDisponibleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbDisponibleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbDisponibleActionPerformed

    private void txtCapacidadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCapacidadKeyTyped
        // TODO add your handling code here:
        char n = evt.getKeyChar();
        if(!Character.isDigit(n)&& n  != '\b'){evt.consume();}
        
    }//GEN-LAST:event_txtCapacidadKeyTyped

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        // TODO add your handling code here:
        if(!validarCampos())return;
        LocalDate fecha = txtFecha.getDate().toInstant().atZone(java.time.ZoneId.systemDefault()).toLocalDate();
        String estado = "";
        if(rbDisponible.isSelected()){
            estado = "DISPONIBLE";
        }else if (rbFinalizado.isSelected()){
            estado = "FINALIZADO";
        }else if(rbCancelado.isSelected()){
            estado = "CANCELADO";
        }
        
        if (Integer.parseInt(txtCapacidad.getText())<=0){
            JOptionPane.showMessageDialog(null, "Ingresa un valor valido");
        
        }else{
            controlador.actualizarPartido(idSelected, txtLocal.getText(),
                txtVisitante.getText(), fecha, cbEstadio.getSelectedItem().toString(), cbCuidad.getSelectedItem().toString(), 
                Integer.parseInt(txtCapacidad.getText()), estado, cbFase.getSelectedItem().toString());
        }
        
        cargarPartidos();
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void jtPartidosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtPartidosMouseClicked
        // TODO add your handling code here:
        cargarDatosCampos();
    }//GEN-LAST:event_jtPartidosMouseClicked
    
    private void cargarPartidos(){
        modeloPartido.setRowCount(0);
        for(ModelGestionPartidos partido: controlador.ObtenerPartido()){
            modeloPartido.addRow(new Object[]{partido.getId(), partido.getLocal(), partido.getVisitante(),
            partido.getFecha(), partido.getEstadio(), partido.getCuidad(), partido.getCapacidad(), partido.getEstado(), partido.getFase()});
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new GestionPartidosV().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JComboBox<String> cbCuidad;
    private javax.swing.JComboBox<String> cbEstadio;
    private javax.swing.JComboBox<String> cbFase;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtPartidos;
    private javax.swing.JRadioButton rbCancelado;
    private javax.swing.JRadioButton rbDisponible;
    private javax.swing.JRadioButton rbFinalizado;
    private javax.swing.JTextField txtCapacidad;
    private com.toedter.calendar.JDateChooser txtFecha;
    private javax.swing.JTextField txtLocal;
    private javax.swing.JTextField txtVisitante;
    // End of variables declaration//GEN-END:variables
}
