/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import javax.swing.table.DefaultTableModel;
import modelo.ModelGestionPartidos;
import modelo.ModelGestionTickets;
import controlador.GestionTicketsController;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.swing.JOptionPane;


public class GestionTicketsV extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GestionTicketsV.class.getName());
    private final DefaultTableModel modeloPartido = new DefaultTableModel(new Object[]{"ID", "Partido", "Fecha", "Estadio", "Capacidad", "Estado"}, 0);
    private final GestionTicketsController controlador = new GestionTicketsController();
    private List<ModelGestionPartidos> listaPartidos;
    
    

    /**
     * Creates new form GestionTicketsV
     */
    public GestionTicketsV() {
        initComponents();
        jtPartidos.setModel(modeloPartido);
        cargarPartidos();
        cargarPartidosCB();
        txtDisponibilidad.setEditable(false);
        txtNumeroAsientos.setEditable(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cbPartido = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        txtDisponibilidad = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cbTipoAsiento = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        txtPrecio = new javax.swing.JTextField();
        btnCrearTicket = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtNumeroAsientos = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtPartidos = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Disponibilidad:");

        cbPartido.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        cbPartido.addActionListener(this::cbPartidoActionPerformed);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Selecciona un partido:");

        txtDisponibilidad.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Tipo de Asiento:");

        cbTipoAsiento.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        cbTipoAsiento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Palco", "Preferencia", "General" }));
        cbTipoAsiento.addActionListener(this::cbTipoAsientoActionPerformed);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("Precio (Sin IVA):");

        txtPrecio.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

        btnCrearTicket.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnCrearTicket.setText("Crear Ticket");
        btnCrearTicket.addActionListener(this::btnCrearTicketActionPerformed);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("Asientos disponibles en sección:");

        txtNumeroAsientos.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtNumeroAsientos.addActionListener(this::txtNumeroAsientosActionPerformed);

        jtPartidos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtPartidos);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setText("Partidos:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel6)
                                .addComponent(jLabel5)
                                .addComponent(txtPrecio, javax.swing.GroupLayout.DEFAULT_SIZE, 257, Short.MAX_VALUE)
                                .addComponent(txtNumeroAsientos))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel1)
                                .addComponent(cbPartido, 0, 257, Short.MAX_VALUE)
                                .addComponent(txtDisponibilidad)
                                .addComponent(jLabel3)
                                .addComponent(cbTipoAsiento, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(63, 63, 63)
                                .addComponent(btnCrearTicket)))
                        .addGap(78, 78, 78)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 872, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(47, 47, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(15, 15, 15)
                .addComponent(cbPartido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtDisponibilidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(cbTipoAsiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)
                        .addGap(12, 12, 12)
                        .addComponent(txtNumeroAsientos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnCrearTicket, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58)))
                .addGap(36, 36, 36))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCrearTicketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearTicketActionPerformed
    ModelGestionTickets mgt = new ModelGestionTickets();
    GestionTicketsController controller = new GestionTicketsController();
    
    ModelGestionPartidos partidoSeleccionado = (ModelGestionPartidos) cbPartido.getSelectedItem();
    
    int partido_id = partidoSeleccionado.getId();
     String seccion = cbTipoAsiento.getSelectedItem().toString().toUpperCase();
     String noAsiento = controller.generarNumeroAsiento(partido_id, seccion);
    
    mgt.setPartido_id(partido_id);
    mgt.setNumero_asiento(noAsiento);
    mgt.setSeccion(seccion);
    mgt.setPrecio(Double.parseDouble(txtPrecio.getText()));
    mgt.setEstado("DISPONIBLE");
    
    if(controller.generarTicket(mgt)){
         controller.descontarAsiento(partido_id);

        int nuevaDisponibilidad = Integer.parseInt(txtDisponibilidad.getText()) - 1;
        txtDisponibilidad.setText(String.valueOf(nuevaDisponibilidad));
        txtNumeroAsientos.setText(noAsiento);
        
        JOptionPane.showMessageDialog(this, "Ticket creado correctamente" + noAsiento);
    }else{
        JOptionPane.showMessageDialog(this, "No se pudo crear el ticket");
    }
        
    
    
    }//GEN-LAST:event_btnCrearTicketActionPerformed

    private void cbTipoAsientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTipoAsientoActionPerformed
        mostrarDisponibilidadSeccion();
    }//GEN-LAST:event_cbTipoAsientoActionPerformed

    private void cbPartidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbPartidoActionPerformed
    ModelGestionPartidos partido = (ModelGestionPartidos) cbPartido.getSelectedItem();
    
        if(partido != null){
        txtDisponibilidad.setText(String.valueOf(partido.getDisponibilidad()));
        mostrarDisponibilidadSeccion();
        }
    }//GEN-LAST:event_cbPartidoActionPerformed

    private void txtNumeroAsientosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumeroAsientosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumeroAsientosActionPerformed

    private void cargarPartidos(){
        modeloPartido.setRowCount(0);
        
        for (ModelGestionPartidos partido: controlador.ObtenerPartido()){
            modeloPartido.addRow(new Object[]{partido.getId(), partido.getLocal()+" - "+partido.getVisitante(), 
                partido.getFecha(), partido.getEstadio(), partido.getCapacidad(), partido.getEstado()});
        }
    }
    private void mostrarDisponibilidadSeccion() {

    ModelGestionPartidos partido =(ModelGestionPartidos) cbPartido.getSelectedItem();

    if (partido != null && cbTipoAsiento.getSelectedItem() != null) {

        int partido_id = partido.getId();
        int capacidad = partido.getCapacidad();
        
        String seccion =
                cbTipoAsiento.getSelectedItem().toString().toUpperCase();

        int disponibles =
                 controlador.obtenerDisponibilidadSeccion(partido_id, seccion, capacidad);

        txtNumeroAsientos.setText(String.valueOf(disponibles));
    }
}
    
    private void cargarPartidosCB(){
        listaPartidos = controlador.ObtenerPartido();
        cbPartido.removeAllItems();
        
        for(ModelGestionPartidos partidol : listaPartidos){
            cbPartido.addItem(partidol);
        }
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new GestionTicketsV().setVisible(true));
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCrearTicket;
    private javax.swing.JComboBox<ModelGestionPartidos> cbPartido;
    private javax.swing.JComboBox<String> cbTipoAsiento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtPartidos;
    private javax.swing.JTextField txtDisponibilidad;
    private javax.swing.JTextField txtNumeroAsientos;
    private javax.swing.JTextField txtPrecio;
    // End of variables declaration//GEN-END:variables
}
