package vista;



import controlador.Factura;
import controlador.VentaController;
import modelo.ClienteModelo;
import modelo.ModelGestionPartidos;


 
import javax.swing.table.DefaultTableModel;
import javax.swing.*;
import java.util.ArrayList;
import java.util.List;
import modelo.ModelGestionTickets;
 
/**
 *
 * @author melga
 */
public class VentaView extends javax.swing.JFrame {
   private final VentaController controlador = new VentaController();

    
    private final int usuarioId = 1;
    private final String usuarioNombre = "vendedor01";

    private DefaultTableModel modeloDisponibles;
    private DefaultTableModel modeloSeleccionados;

    private final List<ModelGestionTickets> disponibles    = new ArrayList<>();
    private final List<ModelGestionTickets> seleccionados  = new ArrayList<>();

    /**
     * Creates new form VentaView1
     */
    public VentaView() {
        initComponents();
        
        modeloDisponibles = (DefaultTableModel) jtDisponibles.getModel();
        modeloSeleccionados = (DefaultTableModel) jtSeleccionados.getModel();
        
        
        cargarPartidos();
        cargarClientes();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jOptionPane1 = new javax.swing.JOptionPane();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cmbPartido = new javax.swing.JComboBox<>();
        lblFase = new javax.swing.JLabel();
        lblEstadio = new javax.swing.JLabel();
        lblFecha = new javax.swing.JLabel();
        btnRecargarPartidos1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtDisponibles = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtSeleccionados = new javax.swing.JTable();
        btnAgregar = new javax.swing.JButton();
        btnQuitar = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        rbExistente = new javax.swing.JRadioButton();
        rbNuevo = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        cmbCliente = new javax.swing.JComboBox<>();
        btnRecargarClientes = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtDireccion = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        lblIVA = new javax.swing.JLabel();
        lblDescuento = new javax.swing.JLabel();
        lblSubtotal = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btnConfirmar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel16 = new javax.swing.JLabel();
        rbNit = new javax.swing.JRadioButton();
        rbCf = new javax.swing.JRadioButton();
        txtNit = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        rbEfectivo = new javax.swing.JRadioButton();
        rbTarjeta = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setToolTipText("Venta de tickets(usuario)");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel1.setText("Partido");

        jLabel2.setText("Fase");

        jLabel3.setText("Estadio");

        jLabel4.setText("Fecha");

        cmbPartido.addActionListener(this::cmbPartidoActionPerformed);

        lblFase.setText("-  ");

        lblEstadio.setText("-  ");

        lblFecha.setText("-  ");

        btnRecargarPartidos1.setText("↻");
        btnRecargarPartidos1.addActionListener(this::btnRecargarPartidos1ActionPerformed);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cmbPartido, 0, 550, Short.MAX_VALUE)
                            .addComponent(lblFase, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblEstadio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblFecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                    .addContainerGap(640, Short.MAX_VALUE)
                    .addComponent(btnRecargarPartidos1)
                    .addContainerGap()))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cmbPartido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lblFase))
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lblEstadio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lblFecha))
                .addContainerGap(23, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(16, 16, 16)
                    .addComponent(btnRecargarPartidos1)
                    .addContainerGap(96, Short.MAX_VALUE)))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jtDisponibles.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Asiento", "Seccion", "Precio(Q)"
            }
        ));
        jScrollPane1.setViewportView(jtDisponibles);

        jtSeleccionados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Asiento", "Seccion", "Precio(Q)"
            }
        ));
        jScrollPane2.setViewportView(jtSeleccionados);

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(this::btnAgregarActionPerformed);

        btnQuitar.setText("Quitar");
        btnQuitar.addActionListener(this::btnQuitarActionPerformed);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAgregar, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnQuitar, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnAgregar, btnQuitar});

        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(btnAgregar)
                        .addGap(18, 18, 18)
                        .addComponent(btnQuitar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnAgregar, btnQuitar});

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        buttonGroup1.add(rbExistente);
        rbExistente.setSelected(true);
        rbExistente.setText("Cliente existente");
        rbExistente.addActionListener(this::rbExistenteActionPerformed);

        buttonGroup1.add(rbNuevo);
        rbNuevo.setText("Cliente nuevo");
        rbNuevo.addActionListener(this::rbNuevoActionPerformed);

        jLabel5.setText("Cliente");

        btnRecargarClientes.setText("↻");
        btnRecargarClientes.addActionListener(this::btnRecargarClientesActionPerformed);

        jLabel6.setText("Nombre");

        jLabel7.setText("Apellido");

        jLabel8.setText("Telefono");

        jLabel9.setText("Email");

        txtEmail.addActionListener(this::txtEmailActionPerformed);

        jLabel10.setText("Direccion");

        txtDireccion.addActionListener(this::txtDireccionActionPerformed);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(rbExistente)
                        .addGap(18, 18, 18)
                        .addComponent(rbNuevo))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(cmbCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRecargarClientes)))
                .addGap(99, 99, 99)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel9)
                            .addComponent(jLabel8)
                            .addComponent(jLabel6))
                        .addGap(46, 46, 46)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNombre, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {rbExistente, rbNuevo});

        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rbExistente)
                            .addComponent(rbNuevo)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel5)
                                .addComponent(cmbCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnRecargarClientes))
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel8)
                        .addGap(19, 19, 19)
                        .addComponent(jLabel9))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13)
                        .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(12, 12, 12)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 18, Short.MAX_VALUE))
        );

        jPanel5Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {rbExistente, rbNuevo});

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Resumen del pago"));

        jLabel11.setText("Subtotal");

        jLabel13.setText("IVA");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setText("TOTAL:");

        jLabel12.setText("Descuento");

        lblTotal.setBackground(new java.awt.Color(0, 0, 0));
        lblTotal.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTotal.setForeground(new java.awt.Color(153, 51, 0));
        lblTotal.setText("Q 0.00");

        lblIVA.setText("Q 0.00");

        lblDescuento.setText("Q 0.00");

        lblSubtotal.setText("Q 0.00");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addComponent(jLabel14)
                            .addGap(28, 28, 28)
                            .addComponent(lblTotal))
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(18, 18, 18)
                                .addComponent(lblSubtotal))
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                    .addComponent(jLabel13)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblIVA))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                    .addComponent(jLabel12)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(lblDescuento)))))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 338, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(lblSubtotal))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(lblDescuento))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(lblIVA))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(lblTotal))
                .addGap(42, 42, 42))
        );

        btnConfirmar.setBackground(new java.awt.Color(153, 255, 153));
        btnConfirmar.setText("Confirmar");
        btnConfirmar.setToolTipText("");
        btnConfirmar.addActionListener(this::btnConfirmarActionPerformed);

        btnLimpiar.setBackground(new java.awt.Color(153, 51, 0));
        btnLimpiar.setText("Cancelar");
        btnLimpiar.addActionListener(this::btnLimpiarActionPerformed);

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel15.setText("Metodo de pago");

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel16.setText("Documento");

        buttonGroup3.add(rbNit);
        rbNit.setText("Nit");
        rbNit.addActionListener(this::rbNitActionPerformed);

        buttonGroup3.add(rbCf);
        rbCf.setText("C/F");
        rbCf.addActionListener(this::rbCfActionPerformed);

        jLabel17.setText("NIT");

        buttonGroup2.add(rbEfectivo);
        rbEfectivo.setText("EFECTIVO");

        buttonGroup2.add(rbTarjeta);
        rbTarjeta.setText("TARJETA");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(rbEfectivo)
                    .addComponent(rbTarjeta))
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNit, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(rbNit)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(rbCf))))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(jLabel17))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(jLabel16)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator2)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rbNit)
                            .addComponent(rbCf))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtNit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(rbEfectivo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rbTarjeta)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(btnConfirmar)
                        .addGap(18, 18, 18)
                        .addComponent(btnLimpiar)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConfirmar)
                    .addComponent(btnLimpiar))
                .addGap(4, 4, 4)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(386, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbPartidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbPartidoActionPerformed
        onPartidoCambiado();
    }//GEN-LAST:event_cmbPartidoActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        moverASeleccionados();
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnQuitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuitarActionPerformed
        devolverADisponibles();
    }//GEN-LAST:event_btnQuitarActionPerformed

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void txtDireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDireccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDireccionActionPerformed

    private void btnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarActionPerformed
        confirmarVenta();
    }//GEN-LAST:event_btnConfirmarActionPerformed

    private void btnRecargarPartidos1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecargarPartidos1ActionPerformed
        cargarPartidos();
    }//GEN-LAST:event_btnRecargarPartidos1ActionPerformed

    private void rbExistenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbExistenteActionPerformed
        cmbCliente.setEnabled(true);
    btnRecargarClientes.setEnabled(true);
    txtNombre.setEnabled(false);
    txtApellido.setEnabled(false);
    txtTelefono.setEnabled(false);
    txtEmail.setEnabled(false);
    txtDireccion.setEnabled(false);
cargarClientes();
    }//GEN-LAST:event_rbExistenteActionPerformed

    private void rbNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbNuevoActionPerformed
       cmbCliente.setEnabled(false);
    btnRecargarClientes.setEnabled(false);
    txtNombre.setEnabled(true);
    txtApellido.setEnabled(true);
    txtTelefono.setEnabled(true);
    txtEmail.setEnabled(true);
    txtDireccion.setEnabled(true);
    }//GEN-LAST:event_rbNuevoActionPerformed

    private void btnRecargarClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecargarClientesActionPerformed
       cargarClientes();
    }//GEN-LAST:event_btnRecargarClientesActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        limpiar();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void rbCfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbCfActionPerformed
        txtNit.setText("");
        txtNit.setEnabled(false);
    }//GEN-LAST:event_rbCfActionPerformed

    private void rbNitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbNitActionPerformed
       txtNit.setEnabled(true);
       txtNit.requestFocus();
    }//GEN-LAST:event_rbNitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VentaView().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnConfirmar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnQuitar;
    private javax.swing.JButton btnRecargarClientes;
    private javax.swing.JButton btnRecargarPartidos1;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JComboBox<String> cmbCliente;
    private javax.swing.JComboBox<String> cmbPartido;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JOptionPane jOptionPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable jtDisponibles;
    private javax.swing.JTable jtSeleccionados;
    private javax.swing.JLabel lblDescuento;
    private javax.swing.JLabel lblEstadio;
    private javax.swing.JLabel lblFase;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblIVA;
    private javax.swing.JLabel lblSubtotal;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JRadioButton rbCf;
    private javax.swing.JRadioButton rbEfectivo;
    private javax.swing.JRadioButton rbExistente;
    private javax.swing.JRadioButton rbNit;
    private javax.swing.JRadioButton rbNuevo;
    private javax.swing.JRadioButton rbTarjeta;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtNit;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables

//metodos
  // coloca los partidos en el menu
private void cargarPartidos() {
    DefaultComboBoxModel modeloCombo = new DefaultComboBoxModel();
    List<ModelGestionPartidos> partidos = controlador.obtenerPartidos();
    for (ModelGestionPartidos p : partidos) {
        modeloCombo.addElement(p);
    }
    cmbPartido.setModel(modeloCombo);
    if (cmbPartido.getItemCount() > 0) {
        cmbPartido.setSelectedIndex(0);
        onPartidoCambiado();
    }
}

//cuando se cambia de partido cambia la info
private void onPartidoCambiado() {
    int index = cmbPartido.getSelectedIndex();
    if (index < 0) return;

    ModelGestionPartidos p = (ModelGestionPartidos) cmbPartido.getSelectedItem();
    if (p == null) return;

    lblEstadio.setText(p.getEstadio() != null ? p.getEstadio() : "—");
    lblFecha.setText(p.getFecha() != null ? p.getFecha().toString() : "—");
    lblFase.setText(p.getFase() != null ? p.getFase() : "—");

    seleccionados.clear();
    modeloSeleccionados.setRowCount(0);
    cargarTickets(p);
    actualizarResumen();
}


private void cargarTickets(ModelGestionPartidos p) {
    disponibles.clear();
    modeloDisponibles.setRowCount(0);

    List<ModelGestionTickets> tickets = controlador.obtenerTickets(p);

    for (ModelGestionTickets t : tickets) {
        disponibles.add(t);
        modeloDisponibles.addRow(new Object[]{
            t.getId(),
            t.getNumero_asiento(),
            t.getSeccion(),
            String.format("%,.2f", t.getPrecio())
        });
    }
}


private void cargarClientes() {
    DefaultComboBoxModel modeloCombo = new DefaultComboBoxModel();
    for (ClienteModelo cl : controlador.obtenerClientes()) {
        modeloCombo.addElement(cl);
    }
    cmbCliente.setModel(modeloCombo);
}

// actualiza los lbl
private void actualizarResumen() {
    lblSubtotal.setText(String.format("Q %,.2f", controlador.calcularSubtotal(seleccionados)));
    lblDescuento.setText(String.format("Q %,.2f", controlador.calcularDescuento(seleccionados)));
    lblIVA.setText(String.format("Q %,.2f", controlador.calcularIVA(seleccionados)));
    lblTotal.setText(String.format("Q %,.2f", controlador.calcularTotal(seleccionados)));
}

//se mueven los tickets de seleccionado a disponible y viceversa
private void moverASeleccionados() {
    int[] filas = jtDisponibles.getSelectedRows();
    if (filas.length == 0) return;

    List<ModelGestionTickets> mover = new ArrayList<>();
    for (int f : filas) {
        int id = (int) modeloDisponibles.getValueAt(f, 0);
        disponibles.stream().filter(t -> t.getId() == id).findFirst().ifPresent(mover::add);
    }
    for (ModelGestionTickets t : mover) {
        disponibles.remove(t);
        seleccionados.add(t);
        modeloSeleccionados.addRow(new Object[]{
            t.getId(), t.getNumero_asiento(), t.getSeccion(),
            String.format("%,.2f", t.getPrecio())
        });
    }
    reconstruirTabla(modeloDisponibles, disponibles);
    actualizarResumen();
}


private void devolverADisponibles() {
    int[] filas = jtSeleccionados.getSelectedRows();
    if (filas.length == 0) return;

    List<ModelGestionTickets> devolver = new ArrayList<>();
    for (int f : filas) {
        int id = (int) modeloSeleccionados.getValueAt(f, 0);
        seleccionados.stream().filter(t -> t.getId() == id).findFirst().ifPresent(devolver::add);
    }
    for (ModelGestionTickets t : devolver) {
        seleccionados.remove(t);
        disponibles.add(t);
        modeloDisponibles.addRow(new Object[]{
            t.getId(), t.getNumero_asiento(), t.getSeccion(),
            String.format("%,.2f", t.getPrecio())
        });
    }
    reconstruirTabla(modeloSeleccionados, seleccionados);
    actualizarResumen();
}


private void reconstruirTabla(DefaultTableModel modelo, List<ModelGestionTickets> lista) {
    modelo.setRowCount(0);
    for (ModelGestionTickets t : lista) {
        modelo.addRow(new Object[]{
            t.getId(), t.getNumero_asiento(), t.getSeccion(),
            String.format("%,.2f", t.getPrecio())
        });
    }
}

// Venta y factura
private void confirmarVenta() {
    if (seleccionados.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Seleccione al menos un ticket.", "Aviso", JOptionPane.WARNING_MESSAGE);
        return;
    }

    ClienteModelo cliente = resolverCliente();
    if (cliente == null) return;

    String metodoPago = getMetodoPago();
    String facturaNit = getNitDocumento();

    
    String mensajeConfirmacion = String.format(
            "Confirmar venta de %d ticket(s)?\n\n" +
            "Cliente: %s\n" +
            "NIT: %s\n" +
            "Pago: %s\n" +
            "Total: Q %,.2f",
            seleccionados.size(),
            cliente.getNombre() + " " + cliente.getApellido(),
            facturaNit,
            metodoPago,
            controlador.calcularTotal(seleccionados)
    );

    int resp = JOptionPane.showConfirmDialog(this, mensajeConfirmacion, "Confirmar Venta", JOptionPane.YES_NO_OPTION);
    if (resp != JOptionPane.YES_OPTION) return;

    
    boolean ok = controlador.confirmarVenta(cliente, seleccionados, usuarioId, metodoPago, facturaNit);

    if (ok) {
       
        double subtotal = controlador.calcularSubtotal(seleccionados);
        double descuento = controlador.calcularDescuento(seleccionados);
        double iva = controlador.calcularIVA(seleccionados);      
        double total = controlador.calcularTotal(seleccionados);   

        
        String textoRecibo = Factura.generarTextoRecibo(
            cliente, seleccionados, subtotal, descuento, iva, total, metodoPago, facturaNit
        );

        
        javax.swing.JTextArea textArea = new javax.swing.JTextArea(textoRecibo);
        textArea.setFont(new java.awt.Font("Monospaced", java.awt.Font.PLAIN, 12));
        textArea.setEditable(false);
        javax.swing.JScrollPane scrollPane = new javax.swing.JScrollPane(textArea);
        scrollPane.setPreferredSize(new java.awt.Dimension(420, 450));

        JOptionPane.showMessageDialog(this, scrollPane, "Venta Registrada Exitosamente", JOptionPane.INFORMATION_MESSAGE);

       
        int opcion = JOptionPane.showConfirmDialog(this, "¿Desea generar PDF?",
                "Generar PDF", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);

        if (opcion == JOptionPane.YES_OPTION) {
            
            String ruta = Factura.generarPDF(textoRecibo);
            if (ruta != null) {
                JOptionPane.showMessageDialog(this,
                        "PDF guardado en:\n" + ruta,
                        "PDF Generado", JOptionPane.INFORMATION_MESSAGE);
                
                new Thread(() -> {
                    try {
                        Runtime.getRuntime().exec(new String[]{"cmd", "/c", ruta});
                    } catch (Exception ex) {
                        System.out.println("No se pudo abrir: " + ex.getMessage());
                    }
                }).start();
            } else {
                JOptionPane.showMessageDialog(this, "Error al generar el PDF.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }

        limpiar();
    } else {
        JOptionPane.showMessageDialog(this, "Error al registrar la venta.", "Error", JOptionPane.ERROR_MESSAGE);
    }
}

// revisa si existe el cliente o no
private ClienteModelo resolverCliente() {
    if (rbExistente.isSelected()) {
        ClienteModelo cl = (ClienteModelo) cmbCliente.getSelectedItem();
        if (cl == null) {
            JOptionPane.showMessageDialog(this, "Seleccione un cliente.", "Aviso", JOptionPane.WARNING_MESSAGE);
        }
        return cl;
    }

    String nombre   = txtNombre.getText().trim();
    String apellido = txtApellido.getText().trim();
    String email    = txtEmail.getText().trim();

    if (nombre.isEmpty() || apellido.isEmpty() || email.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Nombre, apellido y email son obligatorios.", "Aviso", JOptionPane.WARNING_MESSAGE);
        return null;
    }

    ClienteModelo cl = new ClienteModelo(0, nombre, apellido, txtTelefono.getText().trim(), email, txtDireccion.getText().trim());
    return controlador.guardarCliente(cl) ? cl : null;
}


private void limpiar() {
    seleccionados.clear();
    modeloSeleccionados.setRowCount(0);
    txtNombre.setText("");
    txtApellido.setText("");
    txtTelefono.setText("");
    txtEmail.setText("");
    txtDireccion.setText("");
    txtNit.setText("");
    rbCf.setSelected(true);
    rbEfectivo.setSelected(true);
    if (cmbPartido.getItemCount() > 0) onPartidoCambiado();
    actualizarResumen();
}


public String getMetodoPago() {
    return rbTarjeta.isSelected() ? "TARJETA" : "EFECTIVO";
}


public String getNitDocumento() {
    if (rbCf.isSelected()) return "CF";
    String nitTexto = txtNit.getText().trim();
    return nitTexto.isEmpty() ? "CF" : nitTexto;
}
}